driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.3
    driver:
      box: centos-6.3
      box_url: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.3-x86_64-v20130101.box

suites:
  - name: dev
    run_list:
      - "recipe[cookbook-bms::default]"
    attributes:
